# apiVersion: v1
# kind: Secret
# metadata:
#   name: tls-secret # Replace with your desired secret name
#   # namespace: sunbird # Replace with your namespace (e.g., sunbird)
# type: kubernetes.io/tls
# data:
#   tls.crt: {{ .Values.global.proxy_certificate | b64enc }}
#   tls.key: {{ .Values.global.proxy_private_key | b64enc }}